### ISSUE TITLE
url rewrite.

### ISSUE THREAD

**Issue by p3nj** [joepie91/anonnews2#1]
**_FOR THE USER HAVE SAME PROBLEM LIKE I DID, THE WAY SOLVE THIS IS BELOW**_

I've solve this by add below code in .htaccess

```
 RewriteBase /
 RewriteCond /path/to/web/root/%{REQUEST_FILENAME} !-f
 RewriteCond /path/to/web/root/%{REQUEST_FILENAME} !-d
 RewriteRule ^ rewrite.php [PT]
```

---

My website, witch is locate at www.anontaiwan.org

when I click FAQ/IRC/FORUM link,

it will show 404 error,

what should I do?

I've already chmod -R 777 at rewrite.php it still not work, what should I do now?

please help me...

**Comment by joepie91** [comment]
Hi,

From a quick look, you seem to be running Litespeed, which is mostly compatible with Apache - however, I'm not sure if it also supports newer features like FallbackResource. I'm also not sure if this needs to go in the main Litespeed configuration, or whether .htaccess will also work.

You can try adding this to your Litespeed configuration and restarting/reloading the webserver:

```
FallbackResource /rewrite.php
```

If this doesn't work, you can try the 'old' method by enabling `mod_rewrite` and adding something like this to your configuration:

```
<Directory /var/www>
  RewriteBase /

  RewriteCond /var/www/%{REQUEST_FILENAME} !-f
  RewriteCond /var/www/%{REQUEST_FILENAME} !-d
  RewriteRule ^ rewrite.php [PT]
</Directory>
```

More about this method can be found [here](https://httpd.apache.org/docs/trunk/rewrite/remapping.html#fallback-resource). Make sure that you replace /var/www in the above example, with the document root for your site.

Let me know if you get it to work!
- Sven

**Comment by p3nj** [comment]
Thanks for the super fast reply!(10hr)
because I'm using virtual-webhost, so I decide to use .htaccess way,
I have added 

```
 RewriteBase /
 RewriteCond /path/to/web/root/%{REQUEST_FILENAME} !-f
 RewriteCond /path/to/web/root/%{REQUEST_FILENAME} !-d
 RewriteRule ^ rewrite.php [PT]
```

I can use rewrite.php now!
**but I still can't find how to add Admin or Moderator.**
Ive trying to add Admin user from mysql database, but I saw a hash label.
(I do know it's an encode type but I know nothing about it)

Can you teach me how to add Admin and Moderator user?

Thank you Very much again!

**Comment by joepie91** [comment]
The hashes for the moderator accounts are using plain SHA1 - you should be able to use any SHA1 hash creation tool to create a hash. The moderation panel is a little limited and messy still; that's scheduled to be fixed in the next version :)
- Sven

**Comment by p3nj** [comment]
what should I enter at AccessLevel?
![2013-10-25 1 53 29](https://f.cloud.github.com/assets/1501022/1401399/3b73fb7c-3cd5-11e3-9652-a17f9c53cafa.png)
now I've enter '1' for Accesslevel.

I'm now trying to ad forum category and solve category non-English display '????' problem,

Thanks for the support !  I love you ;)

---

It should be fine about messy panel, I am looking forward about new AnonNews :P

**Comment by joepie91** [comment]
The AccessLevel shouldn't matter much - entering 1 should be good enough. I never got around to implementing the bit of code that actually _used_ the access levels :)
- Sven
