### ISSUE TITLE
CSS Style is missing

### ISSUE THREAD

**Issue by p3nj** [joepie91/anonnews2#3]
![2013-10-25 2 53 28](https://f.cloud.github.com/assets/1501022/1401886/99de2040-3cdd-11e3-9eb1-2356d91bfae3.png)

After I add Admin via phpMySql , after Login and logout, CSS style is disappear.

Im sure both filename is both same, but it still have no style with php warning but no related with css.

```
[24-Oct-2013 11:32:40] PHP Warning:  Invalid argument supplied for foreach() in /path/to/public_html/module.forum.overview.php on line 21
```

**Comment by joepie91** [comment]
As for the CSS style; it seems to send all requests for /style2.css to rewrite.php also - that might be a misconfiguration in your rewrite rules. Have a look at your Litespeed (error) logs to check if it says anything about it there. Especially check your configuration to make sure it only sends requests for _non-existent_ pages to /rewrite.php, and not _every_ request.

As for the PHP warning; that only occurs when you have no forum categories. You can safely ignore it; once you add a forum category, it will go away.

**Comment by p3nj** [comment]
Thanks for the tips, after I delete /path/to/web/root on rewrite rules, the problem is removed.

please close this issue, and url rewrite one.

now the only problem is the recaptcha problem.
