### ISSUE TITLE
Vimeo parsing on anonnews.org

### ISSUE THREAD

**Issue by AnonDiscord** [joepie91/anonnews2#4]
I would like to be able to make Anonymous press releases on vimeo, but at the moment only YouTube video links are automatically shown as an embedded video player.

**Comment by joepie91** [comment]
This is implemented and currently live on anonnews.org; however, the repository is currently not in sync with the live site. It will be added to the repository soon, but you can already use it when submitting press releases.

EDIT: For clarity; you can just paste the Vimeo URL into the press release, and it will be turned into an embedded player. Don't paste the embed code itself; it will be ignored.
